### ISSUE TITLE
About dataset preparation

### ISSUE THREAD

**Issue by yifei-he** [EnnengYang/AdaMerging#1]
Hi,

Congratulations on the acceptance of your work!

I am trying to reproduce the result, but run into some troubles preparing the datasets, especially for SUN397, RESISC45, EuroSAT and DTD. Although it is somewhat mentioned in this [issue](https://github.com/mlfoundations/task_vectors/issues/1), it is not fully resolved. I wonder whether you can share your scripts for preprocessing and preparing the datasets? Thanks!

**Comment by EnnengYang** [comment]
Hi,

Thank you for your interest in our work.

I uploaded a processed dataset to [Baidu Cloud disk](https://pan.baidu.com/s/1w0Z2UVv3NVmqDhjH8WTOJQ?pwd=kvg6), you can download it directly.

Best Regards

**Comment by yifei-he** [comment]
Great! Thank you so much!
