### ISSUE TITLE
Reproduce EuroSAT Results with ViT-L-14 and ViT-B-32 Models

### ISSUE THREAD

**Issue by farisxiong** [EnnengYang/AdaMerging#6]
Hello,
I am trying to reproduce the results of EuroSAT dataset for the ViT-L-14 and ViT-B-32 models, but I am unable to match the performance reported in the paper. I would appreciate any guidance or suggestions on how to resolve this issue. Here are the details of my experiments:

ViT-L-14 Model:
My reproduced result: 92.70% accuracy
Reported result in the paper: 94.1% accuracy
ViT-B-32 Model:
My reproduced result: 77.22% accuracy
Reported result in the paper: 78.9% accuracy

Thanks for your assistance and support.

**Comment by EnnengYang** [comment]
Hello,

Thank you for your attention.

You show the baseline result for Task Arithmetic, for which we set the merge coefficient to 0.3 by default.

More importantly, **did you download the dataset from the link I provided** (i.e., [Baidu Cloud disk](https://pan.baidu.com/s/1w0Z2UVv3NVmqDhjH8WTOJQ?pwd=kvg6))? Or did you preprocess it yourself?

Sincerely,

**Comment by farisxiong** [comment]
Thank you for your response. 

We have fully utilized the provided model and the processed dataset, and the results on other datasets are entirely reproducible.
